config/routes.rb
Rails.application.routes.draw do
  # get "todos/index"
  # get "todos/show"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  # resources :todos
  resources :todos, only: [:index, :create, :show, :edit, :update, :destroy] do
    post :toggle, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if(current_user)
      @todos = current_user.todos.all
      @new_todo = current_user.todos.new
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :toggle, :destroy]

  def index
    @todos = current_user.todos.all
    @new_todo = current_user.todos.new
  end

  def show
    @todo = current_user.todos.find(params[:id])
  end

  def new
    @todo = current_user.todos.new
  end

  def create
    @todo = current_user.todos.new(todo_params)

    unless @todo.save
      head :unprocessable_entity
    end
  end

  def update
    #     @todo = current_user.todos.find(params[:id])

    #   puts "#{@todo.inspect} is an important task."
    #  respond_to do |format|
    #    if @todo.update(todo_params)
    #     format.turbo_stream { turbo_stream.replace(@todo) }
    #     else
    #       render :index, status: :unprocessable_entity
    #     end
    #   end
    @todo = current_user.todos.find(params[:id])
    @todo.update(todo_params)
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream { turbo_stream.replace(@todo) }
        format.html { redirect_to todos_url, notice: "Todo was successfully updated." }
      else
        render :index, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @todo.destroy
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :is_done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <h1>Todos</h1>
  <ul style="display:flex;flex-direction:column;gap:12px">
    <%= turbo_frame_tag "todos" do %>
      <%= render @todos %>
    <% end %>
  </ul>
  <%= form_with model: @new_todo, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, class: "form" do |form| %>
    <%= form.text_field :title, placeholder:"Add Task" %>
    <%= form.submit "Create Todo" %>
  <% end %>
<% else %>
  <%= button_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo.html.erb
<li id="<%= dom_id(todo) %>">
  <div  style="display:flex;gap:1rem">
    <%= form_for todo, remote: true do |f| %>
      <%# remote: true is really just telling the browser to not refresh the page. Do the action that you would normally do, but don't do anything to the page %>
      <%= f.check_box :is_done, class: 'todo-checkbox', checked: todo.is_done, onchange: 'this.form.submit();' %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% end %>
    <%= todo.title %>
    <%= button_to "Delete", todo_path(todo), method: :delete, form: { class: :link, data: { turbo_confirm: "Are you sure?" } } %>
  </div>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.append "todos", @todo %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo) %>

app/views/todos/index.html.erb
<h1>Todos</h1>
<ul style="display:flex;flex-direction:column;gap:12px">
  <%= turbo_frame_tag "todos" do %>
    <%= render @todos %>
  <% end %>
</ul>
<%= form_with model: @new_todo, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, class: "form" do |form| %>
  <%= form.text_field :title, placeholder:"Add Task" %>
  <%= form.submit "Create Todo" %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/todos/new.html.erb
<h1>Add todo</h1>
<%= turbo_frame_tag "todo_form" do %>
  <%= render 'shared/todo_form' %>
<% end %>
<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<%= @todo.title %>

<%= link_to 'Back', todos_path %>